-- 코드를 입력하세요

-- SELECT *
-- FROM ONLINE_SALE T1,
-- (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS CNT
-- FROM ONLINE_SALE
-- GROUP BY USER_ID, PRODUCT_ID) T2
-- WHERE 1=1
-- AND T2.CNT > 2
-- AND T1.USER_ID = T2.USER_ID
-- AND T1.PRODUCT_ID = T2.PRODUCT_ID

    SELECT USER_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) >= 2
    ORDER BY USER_ID ASC, PRODUCT_ID DESC;
